services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "5000:5000"
    labels:
      - "database=mongodb"
    env_file: .env
    environment:
      - STEAM_API_KEY=$STEAM_API_KEY
      - DATABASE_URI=mongodb://${DATABASE_ROOT_USERNAME}:${DATABASE_ROOT_PASSWORD}@database:27017/${DATABASE_NAME}?authSource=admin
      - DATABASE_ROOT_USERNAME=$DATABASE_ROOT_USERNAME
      - DATABASE_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
    networks:
      - app-network

  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$DATABASE_NAME
    volumes:
      - ./data/db:/data/db
      - ./data/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
